# .streamlit/config.toml

[theme]
base="light"                  # "light" ou "dark"
primaryColor="#2C7BE5"        # Cor de destaque
backgroundColor="#FFFFFF"     # Fundo principal
secondaryBackgroundColor="#F0F2F6"  # Fundo dos "cards" (blocos)
textColor="#262730"           # Cor de texto
font="sans serif"             # Família de fontes, ex: "serif", "sans serif", "monospace"


[server]
enableXsrfProtection = false
enableCORS = false


[client]
toolbarMode = "minimal"